"""Algebraic-structure CLI commands."""

from __future__ import annotations

from collections.abc import Callable
from typing import TYPE_CHECKING, Annotated

import typer
from rich.console import Console

from cryptolab.cli.common import execute
from cryptolab.exceptions import CryptoLabError
from cryptolab.mathematics.algebra import (
    GroupOperation,
    describe_zn,
    element_order,
    generated_subgroup,
    group_generators,
    primitive_roots,
)
from cryptolab.rendering.algebra import (
    ElementOrderView,
    GeneratedSubgroupView,
    GeneratorCollectionView,
    ZnStructureView,
)

if TYPE_CHECKING:
    from cryptolab.rendering.common import SupportsRender


app = typer.Typer(
    name="algebra",
    help="Inspect finite algebraic structures directly relevant to cryptography.",
    no_args_is_help=True,
)


def _run(context: typer.Context, factory: Callable[[], SupportsRender]) -> None:
    try:
        execute(context, factory())
    except CryptoLabError as error:
        Console(stderr=True, no_color=True).print(f"Error: {error}")
        raise typer.Exit(code=error.exit_code) from error


@app.command("zn", context_settings={"ignore_unknown_options": True})
def zn_command(
    context: typer.Context,
    modulus: Annotated[int, typer.Argument(help="Bounded modulus n, with n >= 2.")],
) -> None:
    """Describe the ring Z_n, its additive group, units, and field status."""

    _run(context, lambda: ZnStructureView(describe_zn(modulus)))


@app.command("order", context_settings={"ignore_unknown_options": True})
def order_command(
    context: typer.Context,
    element: Annotated[int, typer.Argument(help="Residue-class representative.")],
    modulus: Annotated[int, typer.Argument(help="Bounded modulus n, with n >= 2.")],
    operation: Annotated[
        GroupOperation,
        typer.Option("--operation", "-o", help="Select additive or multiplicative order."),
    ] = GroupOperation.ADDITIVE,
) -> None:
    """Compute an element order in (Z_n,+) or the multiplicative unit group."""

    _run(context, lambda: ElementOrderView(element_order(element, modulus, operation)))


@app.command("subgroup", context_settings={"ignore_unknown_options": True})
def subgroup_command(
    context: typer.Context,
    element: Annotated[int, typer.Argument(help="Residue-class representative.")],
    modulus: Annotated[int, typer.Argument(help="Bounded modulus n, with n >= 2.")],
    operation: Annotated[
        GroupOperation,
        typer.Option("--operation", "-o", help="Select additive or multiplicative subgroup."),
    ] = GroupOperation.ADDITIVE,
) -> None:
    """Enumerate the subgroup generated by one element."""

    _run(
        context,
        lambda: GeneratedSubgroupView(generated_subgroup(element, modulus, operation)),
    )


@app.command("generators", context_settings={"ignore_unknown_options": True})
def generators_command(
    context: typer.Context,
    modulus: Annotated[int, typer.Argument(help="Bounded modulus n, with n >= 2.")],
    operation: Annotated[
        GroupOperation,
        typer.Option("--operation", "-o", help="Select additive or multiplicative group."),
    ] = GroupOperation.ADDITIVE,
) -> None:
    """Enumerate all generators of the selected finite group."""

    _run(context, lambda: GeneratorCollectionView(group_generators(modulus, operation)))


@app.command("primitive-roots", context_settings={"ignore_unknown_options": True})
def primitive_roots_command(
    context: typer.Context,
    prime: Annotated[int, typer.Argument(help="Bounded prime modulus p.")],
) -> None:
    """Enumerate every primitive root modulo a prime."""

    _run(
        context,
        lambda: GeneratorCollectionView(
            primitive_roots(prime),
            command="algebra.primitive-roots",
        ),
    )
