"""Educational computations for algebraic structures used in cryptography."""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from math import gcd as math_gcd
from typing import TYPE_CHECKING

from cryptolab.exceptions import MathematicalDomainError, ResourceLimitError
from cryptolab.limits import MAX_ENUMERATED_MODULUS
from cryptolab.mathematics.integers import is_prime

if TYPE_CHECKING:
    from collections.abc import Iterable

MIN_MODULUS = 2


class GroupOperation(StrEnum):
    """Supported finite group operations."""

    ADDITIVE = "additive"
    MULTIPLICATIVE = "multiplicative"


@dataclass(frozen=True, slots=True)
class ZnStructureResult:
    """Structural properties of the residue-class ring Z_n."""

    modulus: int
    is_prime_modulus: bool
    additive_group_order: int
    unit_group_order: int
    units: tuple[int, ...]
    nonzero_zero_divisors: tuple[int, ...]
    additive_group_is_cyclic: bool
    unit_group_is_abelian: bool
    is_commutative_ring_with_identity: bool
    is_integral_domain: bool
    is_field: bool


@dataclass(frozen=True, slots=True)
class GroupPowerStep:
    """One power or repeated-addition value in a finite cyclic orbit."""

    exponent: int
    value: int


@dataclass(frozen=True, slots=True)
class ElementOrderResult:
    """Order of an element in an additive group or multiplicative unit group."""

    element: int
    normalized_element: int
    modulus: int
    operation: GroupOperation
    identity: int
    ambient_group_order: int
    order: int
    steps: tuple[GroupPowerStep, ...]


@dataclass(frozen=True, slots=True)
class GeneratedSubgroupResult:
    """Subgroup generated by one residue-class element."""

    element: int
    normalized_element: int
    modulus: int
    operation: GroupOperation
    order: int
    elements: tuple[int, ...]


@dataclass(frozen=True, slots=True)
class GeneratorCollectionResult:
    """Every generator of a bounded additive or multiplicative group."""

    modulus: int
    operation: GroupOperation
    ambient_group_order: int
    cyclic: bool
    generators: tuple[int, ...]


def _validate_bounded_modulus(modulus: int) -> None:
    if modulus < MIN_MODULUS:
        raise MathematicalDomainError("A modulus must be an integer greater than or equal to 2.")
    if modulus > MAX_ENUMERATED_MODULUS:
        raise ResourceLimitError(
            f"Algebraic enumeration accepts moduli at most {MAX_ENUMERATED_MODULUS}."
        )


def _units(modulus: int) -> tuple[int, ...]:
    return tuple(value for value in range(modulus) if math_gcd(value, modulus) == 1)


def describe_zn(modulus: int) -> ZnStructureResult:
    """Describe cryptographically relevant algebraic properties of Z_n."""

    _validate_bounded_modulus(modulus)
    units = _units(modulus)
    zero_divisors = tuple(value for value in range(1, modulus) if math_gcd(value, modulus) != 1)
    prime_modulus = is_prime(modulus).is_prime
    return ZnStructureResult(
        modulus=modulus,
        is_prime_modulus=prime_modulus,
        additive_group_order=modulus,
        unit_group_order=len(units),
        units=units,
        nonzero_zero_divisors=zero_divisors,
        additive_group_is_cyclic=True,
        unit_group_is_abelian=True,
        is_commutative_ring_with_identity=True,
        is_integral_domain=prime_modulus,
        is_field=prime_modulus,
    )


def _validate_multiplicative_element(element: int, modulus: int) -> int:
    normalized = element % modulus
    if math_gcd(normalized, modulus) != 1:
        raise MathematicalDomainError(
            "Multiplicative element order is defined here only for units of Z_n."
        )
    return normalized


def element_order(
    element: int,
    modulus: int,
    operation: GroupOperation,
) -> ElementOrderResult:
    """Compute an element order with a complete bounded orbit trace."""

    _validate_bounded_modulus(modulus)
    normalized = element % modulus

    if operation is GroupOperation.ADDITIVE:
        identity = 0
        ambient_order = modulus
        order = modulus // math_gcd(normalized, modulus)
        steps = tuple(
            GroupPowerStep(exponent=exponent, value=(exponent * normalized) % modulus)
            for exponent in range(order + 1)
        )
    else:
        normalized = _validate_multiplicative_element(element, modulus)
        identity = 1
        ambient_order = len(_units(modulus))
        values: list[GroupPowerStep] = [GroupPowerStep(exponent=0, value=identity)]
        current = identity
        order = 0
        for exponent in range(1, ambient_order + 1):
            current = (current * normalized) % modulus
            values.append(GroupPowerStep(exponent=exponent, value=current))
            if current == identity:
                order = exponent
                break
        if order == 0:  # pragma: no cover
            raise ArithmeticError("Internal multiplicative-order invariant failure.")
        steps = tuple(values)

    return ElementOrderResult(
        element=element,
        normalized_element=normalized,
        modulus=modulus,
        operation=operation,
        identity=identity,
        ambient_group_order=ambient_order,
        order=order,
        steps=steps,
    )


def generated_subgroup(
    element: int,
    modulus: int,
    operation: GroupOperation,
) -> GeneratedSubgroupResult:
    """Enumerate the subgroup generated by one bounded residue-class element."""

    result = element_order(element, modulus, operation)
    elements = tuple(step.value for step in result.steps[:-1])
    if len(set(elements)) != result.order:  # pragma: no cover
        raise ArithmeticError("Internal generated-subgroup invariant failure.")
    return GeneratedSubgroupResult(
        element=element,
        normalized_element=result.normalized_element,
        modulus=modulus,
        operation=operation,
        order=result.order,
        elements=elements,
    )


def group_generators(
    modulus: int,
    operation: GroupOperation,
) -> GeneratorCollectionResult:
    """Enumerate all generators of the selected bounded group."""

    _validate_bounded_modulus(modulus)
    candidates: Iterable[int]
    if operation is GroupOperation.ADDITIVE:
        ambient_order = modulus
        candidates = range(modulus)
    else:
        unit_values = _units(modulus)
        ambient_order = len(unit_values)
        candidates = unit_values

    generators = tuple(
        candidate
        for candidate in candidates
        if element_order(candidate, modulus, operation).order == ambient_order
    )
    return GeneratorCollectionResult(
        modulus=modulus,
        operation=operation,
        ambient_group_order=ambient_order,
        cyclic=bool(generators),
        generators=generators,
    )


def primitive_roots(prime: int) -> GeneratorCollectionResult:
    """Enumerate primitive roots modulo a bounded prime."""

    _validate_bounded_modulus(prime)
    if not is_prime(prime).is_prime:
        raise MathematicalDomainError(
            "Primitive-root enumeration in CryptoLab requires a prime modulus."
        )
    return group_generators(prime, GroupOperation.MULTIPLICATIVE)
